version: 2
updates:
  # raise PRs for gem updates
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
