---
version: "3.5"
services:
  kohinga:
    image: kohinga:latest
    container_name: kohinga
    environment:
      - PUID=1001
      - PGID=1001
      - USER_UID=1001
      - USER_GID=1001
      - TZ=Europe/Berlin
    volumes:
      - /srv/data/kohinga/db:/app/data/db
      - /srv/data/kohinga/public/images:/app/public/images
      - /srv/media/Images:/app/data/images:ro
    ports:
      - 4567:4567
    restart: unless-stopped
