---
version: "3.5"
services:
  bronko.media.server:
    image: rwaffen/bronko.media.server:main
    container_name: bronko.media.server
    environment:
      - PUID=1001
      - PGID=1001
      - USER_UID=1001
      - USER_GID=1001
      - TZ=Europe/Berlin
    volumes:
      # - /srv/data/bronko.media.server/db:/app/data/db
      - /srv/data/bronko.media.server/public/images:/app/public/images
      - /srv/media/Images:/app/data/images:ro
    ports:
      - 4567:4567
    restart: unless-stopped

  bronko.media.db:
    image: linuxserver/mariadb
    container_name: bronko.media.db
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=R00T_Pa$$w0rd
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=BronkoMediaServer
      - MYSQL_USER=bronko
      - MYSQL_PASSWORD=U$3R_PWd
    volumes:
      - /srv/data/bronko.media.db/config:/config
    restart: unless-stopped
