---
version: "3.5"
services:
  bronko.media.server:
    image: bronko.media:latest
    container_name: bronko.media.server
    environment:
      - PUID=1001
      - PGID=1001
      - USER_UID=1001
      - USER_GID=1001
      - TZ=Europe/Berlin
    volumes:
      - ./data/images:/app/data/images
    ports:
      - 4567:4567
    restart: unless-stopped

  bronko.media.db:
    image: mysql:8.0.25
    container_name: bronko.media.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3t!12345
      MYSQL_PASSWORD: password
      MYSQL_USER: bronko
      MYSQL_DATABASE: BronkoMediaServer
    volumes:
      - ./tmp/testdb/config:/config
    restart: unless-stopped
