---
version: "3.5"
services:
  bronko.media:
    image: rwaffen/bronko.media.server:main
    container_name: bronko.media
    environment:
      - PUID=1001
      - PGID=1001
      - USER_UID=1001
      - USER_GID=1001
      - TZ=Europe/Berlin
    volumes:
      - /srv/data/bronko.media/db:/app/data/db
      - /srv/data/bronko.media/public/images:/app/public/images
      - /srv/media/Images:/app/data/images:ro
    ports:
      - 4567:4567
    restart: unless-stopped
