---
version: "3.9"
services:
  bronko.media.server:
    image: ghcr.io/bronko-media/bronko.media.server:development
    container_name: bronko.media.server
    environment:
      - PUID=1001
      - PGID=1001
      - USER_UID=1001
      - USER_GID=1001
      - TZ=Europe/Berlin
    volumes:
      - ./data/images:/bronko.media/data/images
      - ./config/settings.yml:/bronko.media/config/settings.yml
    ports:
      - 4567:4567
    restart: unless-stopped
    depends_on:
      bronko.media.db:
        condition: service_healthy

  bronko.media.db:
    image: mysql:8.0.34
    container_name: bronko.media.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3t!12345
      MYSQL_PASSWORD: password
      MYSQL_USER: bronko
      MYSQL_DATABASE: BronkoMediaServer
    volumes:
      - ./tmp/testdb/config:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 60s
      timeout: 5s
      retries: 5
