# frozen_string_literal: true

require 'action_view'
require 'config'
require 'digest'
require 'fileutils'
require 'json'
require 'logger'
require 'mini_magick'
require 'pagy'
require 'parallel'
require 'rackup'
require 'rack/handler/puma'
require 'securerandom'
require 'sinatra/base'
require 'sinatra/activerecord'
require 'sinatra/custom_logger'
require 'streamio-ffmpeg'
require 'timeout'
require 'yaml'

Config.load_and_set_settings File.expand_path('settings.yml', __dir__)

require_relative '../lib/bronko_media/version'
require_relative '../lib/bronko_media/database'
require_relative '../lib/bronko_media/models/image'
require_relative '../lib/bronko_media/models/folder'
require_relative '../lib/bronko_media/models/tag'
require_relative '../lib/bronko_media/services/service'
require_relative '../lib/bronko_media/services/thumbnail_service'
require_relative '../lib/bronko_media/services/image_service'
require_relative '../lib/bronko_media/services/folder_service'
require_relative '../lib/bronko_media/services/duplicate_scanner'
require_relative '../lib/bronko_media/services/indexer'
