---
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: data/db/development.sqlite3

production:
  <<: *default
  database: data/db/production.sqlite3
