---
thumb_path: "/images/thumbs"
originals_path: data/images
thumb_target: public/images/thumbs
thumb_res: 300x400^
image_extentions:
- jpg
- jpeg
- png
images_per_page: '30'
col_options: col-md-3
sort_order: DESC
