---
thumb_path: images/thumbs
originals_path: data/images
thumb_target: public/images/thumbs
thumb_res: 300x400^
image_extentions:
- jpg
- jpeg
- png
- webp
- gif
movie_extentions:
- avi
- m4v
- mkv
- mov
- mp4
- mpeg
- ts
images_per_page: 30
col_options: col-md-3
sort_order: DESC
threads: 10
db_adapter: mysql2
db_name: BronkoMediaServer
db_username: bronko
db_password: password
db_host: bronko.media.db
db_ecnoding: utf8mb4
db_collation: utf8mb4_bin
db_pool: '100'
bootstrap_version: '4'
video_do_loop: 'true'
