---
thumb_path: images/thumbs
originals_path: data/images
thumb_target: public/images/thumbs
thumb_res: 300x400^
image_extentions:
- jpg
- jpeg
- png
movie_extentions:
- avi
- m4v
- mkv
- mov
- mp4
- mpeg
- ts
- gif
images_per_page: 30
col_options: col-md-3
sort_order: DESC
db_path: data/db/bronko.media.sqlite3
threads: 10
