name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: |
        bundle config set --local path vendor/bundle
        bundle config set --local with 'development test'
        bundle install

    - name: Run Rubocop
      run: bundle exec rake rubocop

    - uses: voxpupuli/gha-build-and-publish-a-container@v2
      with:
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        buildfile: Dockerfile.debian
        publish: 'false'
        tags: 'ci/dummy:test'
