name: CI🚦

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: |
        bundle config set --local path vendor/bundle
        bundle config set --local with 'development test'
        bundle install

    - name: Run Rubocop
      run: bundle exec rake rubocop

    - uses: voxpupuli/gha-build-and-publish-a-container@v2
      with:
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        publish: 'false'
        tags: 'ci/dummy:test'

  dependabot:
    name: 'Dependabot'
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
